### ISSUE TITLE
snap: missing scripts not exposed as apps?

### ISSUE THREAD

**Issue by phocean** [claudioandre-br/packages#13]
Very good work! Thank you.

I plan to use exclusively the snap package in the future.

But, do you plan to make an app for every other `*2john` script?

Some important ones, like `office2john`, are currently missing.

**Comment by claudioandre-br** [comment]
Hi. This is by design. 

The main reason is because the snap application is **NOT** a `python` **AND** `lua` **AND** `perl` [1] snap package.

Anyway, if you have `python` (or `lua` or `perl`) installed on your system, you can run all `*2john` scripts. Just do this:
```
$ wget https://openwall.info/wiki/_media/john/%D0%B2%CE%B1-%D0%BA_%D1%82%CF%83_%D1%94%CE%B7g%E2%84%93%CE%B1%CE%B7-.doc

$ /snap/john-the-ripper/current/run/office2john.py вα-к_тσ_єηgℓαη-.doc > ~/hash

$ john ~/hash 
Using default input encoding: UTF-8
Loaded 1 password hash (oldoffice, MS Office <= 2003 [MD5/SHA1 RC4 32/64])
Cost 1 (hash type) is 1 for all loaded hashes
Will run 2 OpenMP threads
Proceeding with single, rules:Single
Press 'q' or Ctrl-C to abort, almost any other key for status
Almost done: Processing the remaining buffered candidate passwords, if any.
Proceeding with wordlist:/snap/john-the-ripper/current/run/password.lst, rules:Wordlist
MITM key: 0fa534f3d0
password         (вα-к_тσ_єηgℓαη-.doc)
1g 0:00:00:00 DONE 2/3 (2019-07-06 17:13) 2.127g/s 26742p/s 26742c/s 26742C/s 123456..random
Use the "--show --format=oldoffice" options to display all of the cracked passwords reliably
Session completed
```

[1] To be a snap that is able to run all of these `*2john` scripts, I will have to add many things to the snap package (it would get much bigger).

**Comment by phocean** [comment]
Ok, it makes sense! Thank you!
