### ISSUE TITLE
Why not publish PeaZip?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [claudioandre-br/packages#9]
I believe unofficial snaps can still be published as long as it doesn't use the upstream name (or using it with upstream approval), so why not publishing it?

I notice your package via the b1freearchiver snap in the store.

**Comment by claudioandre-br** [comment]
It was not published because PeaZip misbehave on 64bits machines.  I can't remember the details, but I debugged it inside Lazarus and was able to see it failing. BTW: it was not PeaZip fault, it was Lazarus (or their dependencies) fault.

So, it was not stable as it should be. People should use another alternative (since I need one myself, I pick b1 and I recommend it).

**Comment by Lin-Buo-Ren** [comment]
Thanks for your explanation, and I found the [source recipe](https://github.com/claudioandre-br/packages/commit/ef9136ca785deb3b80eb01ffb024c98553f7b655) in the history just in case I'd like to try it at some time.
